// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3kkUSg5S-oKV6j_nWO8Sc67fx4lSvNYU',
    appId: '1:196678911109:web:0e5d6a06a8ca1e384095ec',
    messagingSenderId: '196678911109',
    projectId: 'xenoverse-pos',
    authDomain: 'xenoverse-pos.firebaseapp.com',
    storageBucket: 'xenoverse-pos.firebasestorage.app',
    measurementId: 'G-QMKNKMXPBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9mFjdnbu07oQTD15Skn2C1WJvzU1qUzE',
    appId: '1:196678911109:android:2d998e88af0175eb4095ec',
    messagingSenderId: '196678911109',
    projectId: 'xenoverse-pos',
    storageBucket: 'xenoverse-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLJq7wPkj311bk_H6d8glcMgsE51N5WwM',
    appId: '1:196678911109:ios:1d279694805385454095ec',
    messagingSenderId: '196678911109',
    projectId: 'xenoverse-pos',
    storageBucket: 'xenoverse-pos.firebasestorage.app',
    androidClientId: '196678911109-9ood6kqbvlktkkkbtimklkecuivb6nl9.apps.googleusercontent.com',
    iosClientId: '196678911109-arjjaae0in2nl7rim7s8addkcvf43p16.apps.googleusercontent.com',
    iosBundleId: 'com.example.xenoverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLJq7wPkj311bk_H6d8glcMgsE51N5WwM',
    appId: '1:196678911109:ios:75a29f98121075534095ec',
    messagingSenderId: '196678911109',
    projectId: 'xenoverse-pos',
    storageBucket: 'xenoverse-pos.firebasestorage.app',
    androidClientId: '196678911109-9ood6kqbvlktkkkbtimklkecuivb6nl9.apps.googleusercontent.com',
    iosClientId: '196678911109-3jepl0qc8u21c1ugb2h99jft9mmifqp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.xenoverse.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3kkUSg5S-oKV6j_nWO8Sc67fx4lSvNYU',
    appId: '1:196678911109:web:a618f70e7d87cd334095ec',
    messagingSenderId: '196678911109',
    projectId: 'xenoverse-pos',
    authDomain: 'xenoverse-pos.firebaseapp.com',
    storageBucket: 'xenoverse-pos.firebasestorage.app',
    measurementId: 'G-0SQYS4087Z',
  );
}
